ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_DELETE_BLOCKED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CATEGORY_DELETED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CATEGORY_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CATEGORY_DELETE_BLOCKED';
