ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PAYMENT_PROVIDER_CONFIGURED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PAYMENT_CREDENTIAL_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'HALF_AND_HALF_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'HALF_AND_HALF_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FLAVOR_ELIGIBILITY_ENABLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'FLAVOR_ELIGIBILITY_DISABLED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_PRICE_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PRODUCT_OPTION_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STORE_FORCE_OPENED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STORE_FORCE_CLOSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STORE_RETURNED_TO_AUTO';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'STORE_AVAILABILITY_OVERRIDE_UPDATED';

ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "pricingSnapshot" JSONB;
ALTER TABLE "OnlineOrderItem" ADD COLUMN IF NOT EXISTS "pricingSnapshot" JSONB;

CREATE INDEX IF NOT EXISTS "AuditLog_organizationId_createdAt_idx" ON "AuditLog"("organizationId", "createdAt");
CREATE INDEX IF NOT EXISTS "AuditLog_organizationId_action_idx" ON "AuditLog"("organizationId", "action");
CREATE INDEX IF NOT EXISTS "AuditLog_organizationId_entity_entityId_idx" ON "AuditLog"("organizationId", "entity", "entityId");
CREATE INDEX IF NOT EXISTS "AuditLog_organizationId_userId_idx" ON "AuditLog"("organizationId", "userId");
