ALTER TYPE "PaymentContextType" ADD VALUE IF NOT EXISTS 'TABLET';
ALTER TYPE "PrintingSource" ADD VALUE IF NOT EXISTS 'TABLET';
ALTER TYPE "DeviceType" ADD VALUE IF NOT EXISTS 'TABLET';
ALTER TYPE "SettingsChannel" ADD VALUE IF NOT EXISTS 'TABLET';
ALTER TYPE "OrderSource" ADD VALUE IF NOT EXISTS 'TABLET';
ALTER TYPE "CustomerSource" ADD VALUE IF NOT EXISTS 'TABLET';
